from dataclasses import dataclass, field
from typing import List

@dataclass
class Trade:
    trade_id: str
    from_team: str
    to_team: str
    give_player_ids: List[str]
    receive_player_ids: List[str]
    status: str = "pending"  # pending, owner_accepted, accepted, rejected
    give_pick_ids: List[str] = field(default_factory=list)
    receive_pick_ids: List[str] = field(default_factory=list)
    # "human" (owner-proposed) or "cpu" (auto-generated by the trade
    # proposal cycle). Drives UI grouping so owners can find CPU offers
    # in their inbox separately from trades they initiated themselves.
    initiated_by: str = "human"
